version: "3"
services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/etc/mysql/conf.d/
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    dns: 114.114.114.114
    environment:
      MYSQL_ROOT_PASSWORD: confluencerootpassword
      MYSQL_DATABASE: confluence
      MYSQL_USER: confluence
      MYSQL_PASSWORD: confluencepassword
    command: [
      "--character-set-server=utf8",
      "--collation-server=utf8_bin",
      "--transaction-isolation=READ-COMMITTED",
      "--max_allowed_packet=256M",
      "--innodb_log_file_size=2GB"
    ]
  
  confluence:
    depends_on:
      - mysql
    image: atlassian/confluence-server:6.6
    restart: always
    ports:
      - "8090:8090"
    dns: 114.114.114.114
